# ===================================================================
# Spring Boot configuration for the "secret-samples" profile.
#
# This configuration overrides the application.yml file.
#
# More information on profiles: https://www.jhipster.tech/profiles/
# More information on configuration properties: https://www.jhipster.tech/common-application-properties/
# ===================================================================

# ===================================================================
# Samples for required secrets to be used in development and ci using prod profile.
# ===================================================================

spring:
  datasource:
    username: dizzyUncle
    password: Docker#2020
jhipster:
  security:
    authentication:
      jwt:
        base64-secret: N2U2YTUwODQ2MjI5MGUzOGRkNzE5MGEwMjY2N2NlNjFjZDkzNTBjZjFmZDc3MmJiYTQ0NzBhYjhlZTlmNDc2NGVjYzZmMjAwZDQwYmJmMzM4Zjc0OWI2MmY3ODQwZmVkNTFkMzMwODRlZjg4MDFiZTc2OGI5ODE3NGFmYTU0ZjY=
