# ===================================================================
# Spring Boot configuration for the "dev" profile.
#
# This configuration overrides the application.yml file.
#
# More information on profiles: https://www.jhipster.tech/profiles/
# More information on configuration properties: https://www.jhipster.tech/common-application-properties/
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

logging:
  level:
    ROOT: DEBUG
    tech.jhipster: DEBUG
    com.daangcool.stack: DEBUG
    org.springframework: INFO   # Spring Boot 기본값 유지
    org.hibernate.SQL: DEBUG    # 실행된 SQL 보여주기
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE # Hibernate 5.x 파라미터
    org.hibernate.orm.jdbc.bind: TRACE # Hibernate 6.x 파라미터

spring:
  devtools:
    restart:
      enabled: true
      additional-exclude: static/**
    livereload:
      enabled: false # we use Webpack dev server + BrowserSync for livereload
  jackson:
    serialization:
      indent-output: true
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:oracle:thin:@//localhost:1521/FREEPDB1
    username: dizzyUncle
    password: Docker#2020
    hikari:
      poolName: Hikari
      auto-commit: false
      maxLifetime: 1800000   # 30분
      idleTimeout: 600000    # 10분
      connectionTimeout: 30000
  liquibase:
    enabled: true
    change-log: classpath:config/liquibase/master.xml
    contexts: dev
    drop-first: false

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true       # SQL 보기 좋게 줄바꿈/들여쓰기
        highlight_sql: true    # 콘솔에서 색상 강조
        use_sql_comments: true # SQL에 주석 포함
        generate_statistics: true # (선택) 실행 통계
    show-sql: false            # System.out 출력은 끄고, 로깅으로만

  mail:
    host: localhost
    port: 1025
    username: ""
    password: ""
    from: "test@stack.local"
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false
  messages:
    cache-duration: PT1S # 1 second, see the ISO 8601 standard
  thymeleaf:
    cache: false

server:
  port: 8443
  # make sure requests the proxy uri instead of the server one
  forward-headers-strategy: native

# ===================================================================
# JHipster specific properties
#
# Full reference is available at: https://www.jhipster.tech/common-application-properties/
# ===================================================================

jhipster:
  cache: # Cache configuration
    redis: # Redis configuration
      expiration: 3600 # By default objects stay 1 hour (in seconds) in the cache
      server: redis://localhost:6379
      cluster: false
      # server: redis://localhost:6379,redis://localhost:16379,redis://localhost:26379
      # cluster: true
  # CORS is only enabled by default with the "dev" profile
  cors:
    # Allow Ionic for JHipster by default (* no longer allowed in Spring Boot 2.4+)
    allowed-origins: 'http://localhost:8100,https://localhost:8443,http://localhost:9000,https://localhost:9000'
    # Enable CORS when running in GitHub Codespaces
    allowed-origin-patterns: 'https://*.githubpreview.dev'
    allowed-methods: '*'
    allowed-headers: '*'
    exposed-headers: 'Authorization,Link,X-Total-Count,X-${jhipster.clientApp.name}-alert,X-${jhipster.clientApp.name}-error,X-${jhipster.clientApp.name}-params'
    allow-credentials: true
    max-age: 1800
  security:
    authentication:
      jwt:
        # This token must be encoded using Base64 and be at least 256 bits long (you can type `openssl rand -base64 64` on your command line to generate a 512 bits one)
        base64-secret: OTM4MjFjMzMyODM1M2I3MmE3NzlmYjkxNDk0NTA2MWNjNTYxNjFmN2M3NjU3MzBmMmIwMGEyMmZjZjZiZDQ1ODIyYTUxYmY4YjlhMjlkMjYxNTBiZDZjZWJiZTAxODE1OTYyNDQ1MmM4MTc5MjgwMzc4ODBjZDgwYzk2YjAzMTk=
        # Token is valid 24 hours
        token-validity-in-seconds: 86400
        token-validity-in-seconds-for-remember-me: 2592000
  mail: # specific JHipster mail property, for standard properties see MailProperties
    base-url: http://127.0.0.1:8080
  logging:
    use-json-format: false # By default, logs are not in Json format
    logstash: # Forward logs to logstash over a socket, used by LoggingConfiguration
      enabled: false
      host: localhost
      port: 5000
      ring-buffer-size: 512
# ===================================================================
# Application specific properties
# Add your own application properties here, see the ApplicationProperties class
# to have type-safe configuration, like in the JHipsterProperties above
#
# More documentation is available at:
# https://www.jhipster.tech/common-application-properties/
# ===================================================================

application:
  logging:
    file-path: ./logs/dev
    max-file-size: 5MB
    max-history: 7
    total-size-cap: 200MB
  file:
    storage-type: LOCAL         # 💡 storage-type을 LOCAL로 명시하거나, 아예 생략해도 됩니다. (기본값)
    upload-dir: /uploads         # DB에 저장될 웹 접근 경로 접두사  💡 upload-dir만 지정하면 됩니다.
    public-path: /uploads/public     #  Public 파일 URL prefix (permitAll)
    private-path: /uploads/private   #  Private 파일 URL prefix (Controller 접근

#aws:
#  s3:
#    region: ap-northeast-2          # 서울 리전
#    bucket: my-bucket-name
#    access-key: YOUR_AWS_ACCESS_KEY
#    secret-key: YOUR_AWS_SECRET_KEY
#oci:
#  namespace: mynamespace
#  bucket: mybucket
#  region: ap-seoul-1
