# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
name: stack
services:
  redis:
    extends:
      file: ./redis.yml
      service: redis
  oracle:
    extends:
      file: ./oracle-23-slim-faststart.yml
      service: oracle
