#!/bin/bash
set -euo pipefail

repo_root="$(cd "$(dirname "$0")/.." && pwd)"
cache_file="$repo_root/docs/analysis/2026-05-16-stack-app-docs-routing-cache/report.md"
tmp_file="$(mktemp)"

mkdir -p "$(dirname "$cache_file")"

cat > "$tmp_file" <<'EOF'
# Stack App Docs Routing Cache

Repo-local summary for agents that need to reuse the docs layout without rescanning the full tree.
Generated by `scripts/sync-docs-routing-cache.sh`.

## Purpose
- Keep the canonical docs locations short and explicit.
- Reduce repeated discovery work for agents that need to know where standards, workflows, operations, logs, and analysis files live.
- Preserve the source docs as the truth; this file is only a cache.

## Canonical Read Order
1. `AGENTS.md`
2. `docs/history.md`
3. `docs/standards/tooling-policy.md`
4. `docs/standards/semble-operation-guide.md`
5. `docs/standards/serena-guide.md`
6. `docs/workflow/agent-workflow-pipeline.md`
7. `docs/workflow/git-workflow.md`
8. `docs/operations/cache-operations.md`
9. `docs/operations/testing-guideline.md`

## docs/ Tree Map
EOF

docs_root="$repo_root/docs"
if [ -d "$docs_root/analysis" ]; then
  printf '%s\n' "- \`docs/analysis/\`: repo-local reports, measurements, and cache summaries" >> "$tmp_file"
fi
if [ -d "$docs_root/archive" ]; then
  printf '%s\n' "- \`docs/archive/\`: older analysis and agent-log history" >> "$tmp_file"
fi
if [ -d "$docs_root/backend/agent-log" ]; then
  printf '%s\n' "- \`docs/backend/agent-log/\`: backend-oriented task logs and templates" >> "$tmp_file"
fi
if [ -d "$docs_root/frontend/agent-log" ]; then
  printf '%s\n' "- \`docs/frontend/agent-log/\`: frontend-oriented task logs and templates" >> "$tmp_file"
fi
if [ -d "$docs_root/knowledge" ]; then
  printf '%s\n' "- \`docs/knowledge/\`: reusable lessons and notes" >> "$tmp_file"
fi
if [ -d "$docs_root/operations" ]; then
  printf '%s\n' "- \`docs/operations/\`: execution how-to and runbooks" >> "$tmp_file"
fi
if [ -d "$docs_root/release-notes" ]; then
  printf '%s\n' "- \`docs/release-notes/\`: versioned release notes" >> "$tmp_file"
fi
if [ -d "$docs_root/standards" ]; then
  printf '%s\n' "- \`docs/standards/\`: mandatory rules, guides, and templates" >> "$tmp_file"
fi
if [ -d "$docs_root/superpowers/plans" ]; then
  printf '%s\n' "- \`docs/superpowers/plans/\`: execution plans for non-trivial tasks" >> "$tmp_file"
fi
if [ -d "$docs_root/workflow" ]; then
  printf '%s\n' "- \`docs/workflow/\`: collaboration, review, CI, and delivery process" >> "$tmp_file"
fi

cat >> "$tmp_file" <<'EOF'
- root docs: `AGENTS.md`, `README.md`, and `docs/history.md`

## Update Rules
- Update source policy docs first.
- Update this cache only after the source docs are settled.
- Keep the cache short; add deltas, do not rewrite history.
- Rebuild this file with `scripts/sync-docs-routing-cache.sh` after docs-tree changes.

## Cross-Repo Note
- Do not assume another repo uses the same `docs/` layout.
- Re-derive the folder map per repository before copying this pattern.
EOF

if [ "${1:-}" = "--check" ]; then
  if ! diff -u "$cache_file" "$tmp_file"; then
    rm -f "$tmp_file"
    exit 1
  fi
  rm -f "$tmp_file"
  exit 0
fi

mv "$tmp_file" "$cache_file"
